language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install flake8
# command to run tests
script:
  - flake8 . --max-line-length=120
# Force docker container build
sudo: false
